theme:
  - image: kimetsu.jpg
    caption: "鬼滅の刃"
    description: |-
      鬼滅の刃は、大正時代を舞台に、鬼に家族を殺された主人公が修業を積み、仲間と共に鬼を討っていく物語です。 
      大正時代を舞台に、家族を鬼に殺された主人公「竈門炭治郎」（かまどたんじろう）が、鬼と化してしまった妹「竈門禰豆子」（かまどねずこ）を人間に戻すため、様々な修業や苦難を乗り越え、仲間と共に鬼を退治していきます。
  - image: pokemon.png
    caption: "ポケモン"
    description: |-
      ポケモンは、ポケットモンスターの略称で、1996年に初めて登場した日本のゲームシリーズです。 
      プレイヤーはポケモントレーナーとなり、ポケモンを捕まえ、育て、バトルを繰り広げます。 
      ポケモンは様々な種類があり、それぞれ異なる能力や特性を持っています。 
      また、ポケモン同士の進化や交換も重要な要素です。
