name: Docker Image CI
run-name: Docker Image CI by ${{ github.actor }} 🚀
env:
  PROJECT_ID: "my-playground-458212"
  LOCATION: "asia-northeast1"
  REPOSITORY: "gcp-streamlit-docker-repo"
  IMAGE: "streamlit"
  TAG: "latest"
  WORKLOAD_IDENTITY_PROVIDER: "projects/1062902222689/locations/global/workloadIdentityPools/github/providers/github" # IAM > Workload Identity 連携から取得
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      # インスタンスにソースコードをクローン
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      # Configure Workload Identity Federation and generate an access token.
      #
      # See https://github.com/google-github-actions/auth for more options,
      # including authenticating via a JSON credentials file.
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2" # google-github-actions/auth@v2
        with:
          workload_identity_provider: "${{ env.WORKLOAD_IDENTITY_PROVIDER }}"

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: "Docker Auth"
        uses: "docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567" # docker/login-action@v3
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.auth_token }}"
          registry: "${{ env.LOCATION }}-docker.pkg.dev"
      - name: Build the Docker image
        run: |-
          DOCKER_TAG="${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${TAG}"
          cd streamlit && docker build --t ${DOCKER_TAG} .
          docker push "${DOCKER_TAG}"
